authentication/urls.py
from django.urls import path 

from authentication.views import (
    login, logout, signup,
)

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup"),
]

app_name = "authentication"

blog/urls.py
from django.urls import path

from .views.blog import (
    post_list, post_detail, post_add, edit_post, my_stories,
    post_by_tag, delete_post,
    add_post_comment,
)

from .views import errors


app_name = 'blog'

urlpatterns = [
    path('all/', post_list, name="post_list"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', post_detail, name="post_detail"),
    path('post/new/', post_add, name="post_add"),
    path('post/<slug:slug>/edit/', edit_post, name="post_edit"),
    path('post/delete/<int:year>/<int:month>/<int:day>/<slug:slug>/', delete_post, name="post_delete"),
    path('post/my_stories/', my_stories, name="my_stories"),
    path('all/tags/<slug:slug>/', post_by_tag, name="post_by_tag"),
    path('post/<slug:slug>/comment/add/', add_post_comment, name="add_post_comment"),
]

#  Error views
handler404 = errors.handler404

kaliblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blog.views.blog import index


urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('posts/', include('blog.urls', namespace='blog')),
    path('authentication/', include('authentication.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blog.views import index


urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('posts/', include('blog.urls', namespace='blog')),
    path('authentication/', include('authentication.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _ 


class UserManager(BaseUserManager):
    """Object Manager for the Custom User Model
    """

    def create_user(self, email, first_name, last_name, password=None, commit=True):
        """Creates, saves and returns a user with normal privileges
        :param email:
        :param first_name:
        :param last_name:
        :param password:
        :param commit:
        """

        if not email:
            raise ValueError("User must provide email")

        if not first_name:
            raise ValueError("User must provide first_name")

        if not last_name:
            raise ValueError("User must provide last_name")

        if not password:
            raise ValueError("User must provide password")


        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            #password=password
        )

        user.set_password(password)

        if commit:
            user.save(using=self._db)
        
        return user 

    def create_superuser(self, email, first_name, last_name, password):
        """Creates, saves and returns a user with administrator privileges
        
        :param email:
        :param first_name:
        :param last_name:
        :param password:
        """

        user = self.create_user(
            email=email,
            first_name=first_name,
            last_name=last_name,
            password=password,
            commit=False
        )

        user.is_staff = True 
        user.is_superuser = True
        user.save(using=self._db)

        return user 


class User(AbstractBaseUser, PermissionsMixin):
    """The Custom User Model
    """

    email = models.EmailField(
        verbose_name=_("email_address"),
        max_length=255,
        unique=True,
    )

    # password field is provided by the AbstractBaseUser model

    first_name = models.CharField(
        verbose_name=_("first_name"),
        max_length=100,
        blank=True
    )

    last_name = models.CharField(
        verbose_name=_("last_name"),
        max_length=100,
        blank=True
    )

    # is_superuser, groups and permissions are provided by the PermissionsMixin model

    is_active = models.BooleanField(
        _("active status"),
        default=True,
        help_text=_(
            "Designates whether a user is active or not"
            "This is unselected in the case of a delete"    
        )
    )

    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_(
            "Designates whether a user is a staff or not"
        )
    )

    groups = []
    user_permissions = []

    date_joined = models.DateTimeField(
        _("date joined"),
        default=timezone.now
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def __str__(self):
        return "{} <{}>".format(self.full_name(), self.email)

    def has_perm(self, perm, obj=None):
        """
        Does the user have a specific permission?
        Always Yes
        :param perm:
        :param obj:
        :return:
        """
        return True 

    def has_module_perms(self, app_label):
        """
        Does the user have the permission to view the app_label?
        Always Yes
        :param app_label:
        :return:
        """
        return True 

authentication/forms.py
from django import forms 

from authentication.models import User 


class UserLoginForm(forms.Form):
    username = forms.EmailField(max_length=255)
    password = forms.CharField(max_length=255)


class UserRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User 
        fields = ("first_name", "last_name", "email")

    def clean_password2(self):
        data = self.cleaned_data
        if data['password1'] != data['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return data['password2']

    def clean_email(self):
        return self.cleaned_data.get("email").lower()

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_method 
from django.contrib.auth import logout as logout_method
from django.urls import reverse 
from django.contrib import messages

from authentication.forms import UserLoginForm, UserRegistrationForm


def login(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username").lower()
            password = form.cleaned_data.get("password")

            user = authenticate(username=username, password=password)
            if user:    
                login_method(request, user)
                next_url = request.GET.get("next")
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect(reverse("home"))
            else:
                messages.error(request, "Invalid Username or Password")
                return redirect(reverse("authentication:login"))
        else:
            import pdb; pdb.set_trace()         # For Development Purposes

    template = "authentication/login.html"
    form = UserLoginForm()
    context = {"form": form}
    return render(request, template, context)


def logout(request):
    logout_method(request)
    return redirect(reverse("home"))


def signup(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password1"])
            user.save()
            return redirect(reverse("home"))
        else:
            import pdb; pdb.set_trace()
            messages.error(request, form.errors)
            
    template = "authentication/signup.html"
    form = UserRegistrationForm()
    context = {"form": form}
    return render(request, template, context)

templates/authentication/login.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style_link %} <link rel="stylesheet" href="{% static 'css/auth.css' %}" /> {% endblock %}


{% block header %}{% endblock %}

{% block start_container %}

    <div class="container text-center">
        {% for message in messages %}
            {% if message.tags == 'alert-danger' %}
                <div class="alert {{ message.tags }} text-danger p-1 alert-dismissable" role="alert">
                    <!-- <p> -->
                        <span>Invalid Username or Password
                            <!-- <span style="cursor: pointer;" type="span" class="close text-danger" data-dismiss="alert" aria-label="Close">
                                &times;
                            </span> -->
                        </span>
                    <!-- </p> -->
                    
                </div>
            {% endif %}

        {% endfor %}
        <form action="" method="POST" class="form-signin shadow-lg p-5 rounded">
            {% csrf_token %}
            <h1 class="h3 mb-4 font-weight-bold text-primary"><a href="{% url 'home' %}">KaliBlog</a></h1>
            <label for="{{ form.username.id_for_label }}" class="sr-only">Email Address</label>
            <input type="email" class="form-control mb-2" id="{{ form.username.id_for_label }}" 
                name="{{ form.username.name }}" placeholder="Email Address" required autofocus 
                autocomplete="off" />
            <label for="{{ form.password.id_for_label }}" class="sr-only">Password</label>
            <input type="password" class="form-control mb-2" id="{{ form.password.id_for_label }}"
                name="{{ form.password.name }}" placeholder="Password" required autocomplete="off" />
            <div class="checkbox mb-3">
                <label class="d-block text-left mt-3">
                    <input type="checkbox" value="remember me"> Remember Me
                </label>
            </div>
            <button class="btn btn-sm btn-block btn-primary rounded">Sign in</button>
            <div class="text-center mt-1">
                <a class="d-block" style="font-size: small" href="#">Forgot Password</a>
                <a style="font-size: small" href="{% url 'authentication:signup' %}">Don't Have an Account?</a>
            </div>
        </form>
    </div>

{% endblock start_container %}

templates/authentication/signup.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style_link %}
    <link rel="stylesheet" href="{% static 'css/auth.css' %}" />
    <style>
        label.placeholder {
            font-size: 14px;
        }

        p.error-text {
            margin-right: 1rem;
        }
    </style>
{% endblock %}


{% block header %}{% endblock %}

{% block start_container %}

    <div class="container">
        {% for message in messages %}
            {% if message.tags == 'alert-danger' %}
                <div class="alert {{ message.tags }} text-danger p-1 alert-dismissable" role="alert">
                    <!-- <p> -->
                        <span>{{ message }}
                            <!-- <span style="cursor: pointer;" type="span" class="close text-danger" data-dismiss="alert" aria-label="Close">
                                &times;
                            </span> -->
                        </span>
                    <!-- </p> -->
                    
                </div>
            {% endif %}

        {% endfor %}
        <form action="" method="POST" class="form-signup shadow-lg p-5 rounded">
            {% csrf_token %}
            <h1 class="h3 mb-4 font-weight-bold text-primary text-center"><a href="{% url 'home' %}">KaliBlog</a></h1>
            <div class="row mb-5">
                <div class="col">

                    <input type="text" class="form-control " id="{{ form.first_name.id_for_label }}"
                        name="{{ form.first_name.name }}" autocomplete="off" required />
                    <label class="placeholder" for="{{ form.first_name.id_for_label }}">First Name <i class="ml-1 icon-user"></i></label>
                </div>
                <div class="col">

                    <input type="text" class="form-control" id="{{ form.last_name.id_for_label }}"
                        name="{{ form.last_name.name }}" autocomplete="off" required />
                    <label class="placeholder" for="{{ form.last_name.id_for_label }}">Last Name <i class="ml-1 icon-user"></i></label>
                </div>
            </div>
            <div class="row mb-5">
                <div class="col">

                    <input type="text" class="form-control " id="{{ form.email.id_for_label }}"
                        name="{{ form.email.name }}" autocomplete="off" required />
                    <label class="placeholder" for="{{ form.email.id_for_label }}">Email <i class="ml-1 icon-envelope"></i> </label>
                </div>

            </div>
            <div class="row mb-5">
                <div class="col">

                    <input type="password" class="form-control" id="{{ form.password1.id_for_label }}"
                        name="{{ form.password1.name }}" autocomplete="off" required/>
                    <label class="placeholder" for="{{ form.password1.id_for_label }}">Password <i class="ml-1 icon-key"></i></label>
                    <p style="font-size: 12px" class="text-danger error-text">Passwords Does not match</p>
                </div>
                    <div class="col">

                    <input type="password" class="form-control" id="{{ form.password2.id_for_label }}"
                        name="{{ form.password2.name }}" autocomplete="off" required/>
                    <label class="placeholder" for="{{ form.password2.id_for_label }}">Confirm Password <i class="ml-1 icon-key"></i></label>
                    <p style="font-size: 12px;" class="text-danger error-text">Passwords Does not match</p>
                </div>
            </div>

            <button type="submit" class="btn btn-sm btn-block btn-primary">Sign up</button>
            <div class="d-flex mt-1">
                <a class="mx-auto" href="{% url 'authentication:login' %}">Login</a>
            </div>
        </form>
    </div>

{% endblock start_container %}

{% block end_container %}
    <script type="text/javascript">
        const inputs = document.querySelectorAll("input.form-control");
        for (let i=0; i<inputs.length; i++) {
            const label = document.querySelector(`#${inputs[i].getAttribute("id")} + .placeholder`)
            inputs[i].onfocus = () =>{
                label.style.transform = "translateY(-2.2rem)";
            }
            inputs[i].onblur = () => {
                if (inputs[i].value == "") {
                    label.style.transform = "translateY(0rem)";
                }
            }
        }

        // Form Password Validation
        const password1 = document.querySelector("#{{ form.password1.id_for_label }}");
        const password2 = document.querySelector("#{{ form.password2.id_for_label }}");

        document.querySelector("form").onsubmit = (e) => {
            if (password1.value != password2.value) {
                Array.from(document.querySelectorAll(".error-text")).map(input=> {input.style.display = "block"});
                return false;
            } else {
                return true
            }
        }

    </script>
{% endblock %}