blog/urls.py
from django.urls import path

from .views.blog import (
    post_list, post_detail, post_add, edit_post, my_stories,
    post_by_tag, delete_post,
    add_post_comment,
)

from .views import errors


app_name = 'blog'

urlpatterns = [
    path('all/', post_list, name="post_list"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', post_detail, name="post_detail"),
    path('post/new/', post_add, name="post_add"),
    path('post/<slug:slug>/edit/', edit_post, name="post_edit"),
    path('post/delete/<int:year>/<int:month>/<int:day>/<slug:slug>/', delete_post, name="post_delete"),
    path('post/my_stories/', my_stories, name="my_stories"),
    path('all/tags/<slug:slug>/', post_by_tag, name="post_by_tag"),
    path('post/<slug:slug>/comment/add/', add_post_comment, name="add_post_comment"),
]

#  Error views
handler404 = errors.handler404

kaliblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blog.views.blog import index


urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('posts/', include('blog.urls', namespace='blog')),
    path('authentication/', include('authentication.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blog.views import index


urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('posts/', include('blog.urls', namespace='blog')),
    path('authentication/', include('authentication.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import random
import uuid

from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse

from taggit.managers import TaggableManager

from .helpers import upload_path, count_words, read_time

"""
Contains Models For The Blog:
1. PostCategory
2. Post
3. Comment

Above are the enlisting of the models in this files in order in
which they were written
"""

User = get_user_model()


#########################################################
#                 POST CATEGORY MODEL
#########################################################
class PostCategoryManager(models.Manager):
    def get_queryset(self):
        return super(PostCategoryManager, self).get_queryset().filter(
            approve=True
        )


class PostCategory(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    image = models.ImageField()
    approve = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('title',)
        verbose_name = 'post_category'
        ordering = ('-updated', )

    objects = models.Manager()
    approved = PostCategoryManager()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(f"{self.title} - {uuid.uuid4()} - {random.randint(1, 9999999999)}", allow_unicode=True)
        super(PostCategory, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})


#########################################################
#                 POST MODEL
#########################################################
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
            .filter(active=True, status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250, unique_for_date='published_date'
    )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    # category = models.ForeignKey(PostCategory, on_delete=models.CASCADE, related_name="posts")
    tags = TaggableManager()
    body = models.TextField()
    image = models.ImageField(upload_to=upload_path)
    views = models.PositiveIntegerField(default=0)
    active = models.BooleanField(default=True)
    words_count = models.PositiveIntegerField(default=0)
    read_duration = models.CharField(max_length=50, default=0)
    published_date = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft'
                              )

    class Meta:
        ordering = ('-published_date', )

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.status

    def save(self, *args, **kwargs):
        self.slug = slugify(f"{self.title} - {random.randint(1, 9999999999)} - {uuid.uuid4()}")
        self.words_count = count_words(self.body)
        self.read_duration = read_time(self.body)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.published_date.year,
                                                 self.published_date.month,
                                                 self.published_date.day, self.slug])

    def get_delete_url(self):
        return reverse('blog:post_delete', args=[self.published_date.year,
                                                 self.published_date.month,
                                                 self.published_date.day, self.slug])


#########################################################
#                 POST COMMENT MODEL
#########################################################
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post_comments")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created', )

    def __str__(self):
        return f'Comment by {self.author.full_name()} on {self.post}'

blog/forms.py
from django import forms

from .models import Comment, PostCategory, Post


class EmailPostForm(forms.Form):
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentPostForm(forms.ModelForm):
    class Meta:
        fields = ("body",)
        model = Comment


class PostCategoryForm(forms.ModelForm):
    class Meta:
        model = PostCategory
        fields = ('title', 'image')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author', 'body', 'image', 'status', 'tags')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail

from .models import Post, PostCategory
from .forms import EmailPostForm, CommentPostForm, PostCategoryForm, PostForm


# TODO: Refactor project and place view functions into different files to encourage project scaling 

def index(request):
    """
    Returns the homepage html
    :param request: -   Request object
    """
    template = "index.html"
    # categories = PostCategory.approved.all()
    posts = Post.objects.all().order_by('-views')
    if len(posts) >= 2:
        featured_posts = posts[:2]
    else:
        featured_posts = None
    context = {
        # 'categories': categories,
        'home_active': 'active',
        "posts": featured_posts
    }
    return render(request, template, context)


def posts_page(request, slug):
    template = "blog/posts/explore.html"
    object_list = Post.objects.filter(category__slug=slug)
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        "posts": posts,
        "page": page,
        "explore_active": "active"
    }
    return render(request, template, context)


class PostListView(ListView):
    """
    This is a Class Based View, It has the exact same functionality as the
    function based view below post_list(request)
    """
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 6
    template_name = "blog/post/list.html"


def post_list(request):
    """
    This is a function based view, It has the exact same functionality as the
    Class Based View above PostListView.
    :param request:
    :return:
    """
    object_list = Post.published.all()
    paginator = Paginator(object_list, 6)   # 6 post in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    template = "blog/posts/explore.html"
    # import pdb; pdb.set_trace()
    context = {
        "posts": posts,
        "page": page,
        "explore_active": "active"
    }
    return render(request, template, context)


def post_add(request):
    if request.method == "POST":
        request.POST = request.POST.copy()
        request.POST["author"] = request.user.pk 
        request.POST["status"] = "published"
        form = PostForm(request.POST, request.FILES)
        # import pdb; pdb.set_trace()
        if form.is_valid():
            instance = form.save()
            return redirect(instance.get_absolute_url())
    template = "blog/posts/new_post.html"
    
    form = PostForm()
    # import pdb; pdb.set_trace()

    categories = PostCategory.approved.all()
    context = {
        "form": form,
        "categories": categories
        }
    return render(request, template, context)


def post_detail(request, year, month, day, slug):
    """
    This function based view gets a particular post with the parameters below
    :param request:
    :param year:
    :param month:
    :param day:
    :param post:
    :return:
    """
    template = "blog/posts/post.html"
    post = get_object_or_404(
        Post, slug=slug,
        status='published',
        published_date__year=year,
        published_date__month=month,
        published_date__day=day
    )

    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None
    if request.method == "POST":
        request.POST = request.POST.copy()
        request.POST["name"] = request.user.username
        request.POST["email"] = request.user.email
        comment_form = CommentPostForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(post.get_absolute_url())
    else:
        comment_form = CommentPostForm(request.GET)
        form = EmailPostForm(request.GET)
        context = {
            "post": post,
            "form": form,
            "comment_form": comment_form,
            "new_comment": new_comment,
            "comments": comments
        }
        return render(request, template, context)


def post_share(request, year, month, day, post):
    """
    A View function that shares posts via email
    :param request:
    :param year:
    :param month:
    :param day:
    :param post:
    :return:
    """
    post = get_object_or_404(Post,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             status='published')
    template = "blog/post/share.html"
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        # import pdb; pdb.set_trace()
        if form.is_valid():
            cd = form.cleaned_data
            # TODO: Send the email
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['first_name']} {cd['last_name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@kaliblog.com', [cd['to']])
            sent = True
        else:
            form = EmailPostForm()
        context = {
            "post": post,
            "form": form,
            "sent": sent
        }
        return render(request, template, context)


###################################################
#           Category View Functions
###################################################
def add_category(request):
    """
    A View Function that adds a category for POST request and returns category add template for get request
    :param request
    """
    if request.method == "POST":
        form = PostCategoryForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.approve = True
            instance.save()
            return redirect("home")
    
    template = "blog/post_category/add.html"
    form = PostCategoryForm()
    context = {
        "form": form
    }
    return render(request, template, context)

blog/views/errors.py
from django.shortcuts import render


def handler404(request, exception):
    template = "errors/404.html"
    # context = {}
    return render(request, template, status=404)

templates/blog/posts/edit_post.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style_link %}
<script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}" ></script>
<script type="text/javascript">
    tinymce.init({
        selector: "#{{ form.body.id_for_label | safe }}",
        toolbar: false,
        menubar: false,
        plugins: "autoresize quickbars image media table hr",
        quickbars_selection_toolar: "bold italic link | h1 h2 | blockquote",
        quickbars_insert_toolbar: "image media table hr",
    //     // skin: "snow",
        placeholder: "Share your story...",
        content_style: "@import url('https://fonts.googleapis.com/css2?family=Tinos&display=swap'); body { font-family: 'Tinos', serif; font-size: 16pt; }",
        showPreview: true,
    });


</script>

<style>
    header {
        margin-bottom: 4rem;
    }

    .title {
        border-top: none;
        border-left: none;
        border-right: none;
        border-radius: 0;
        border-bottom-width: 2px;
        font-size: 1.2rem;
    }

    .title:focus {
        outline: none;
        box-shadow: none;
        border-color: #ced4da;
    }

    .image::-webkit-file-upload-button {
        color: red!important;
    }

    input#{{ form.image.id_for_label }} {
        display: none;  
    }

    #imagePreview {
        background-size: cover;
        background-position: center;
        background-image: url('{{ post.image.url }}');
        width: 100%;
        height: 40vh;
        /* display: none; */
    }

    .tox.tox-tinymce {
        border: none;
    }

    .tox-statusbar {
        display: none!important;
    }

</style>
{% endblock %}


{% block start_container %}
    <main class="container form-container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form class="mb-5" enctype="multipart/form-data" method="POST" action="{% url 'blog:post_edit' post.slug %}">
                    {% csrf_token %}
                    <input class="image" value="{{ post.image.url }}" type="file" name="{{ form.image.name }}" id="{{ form.image.id_for_label }}">
                    <!-- <h2 class="dfree-header mce-content-body" contenteditable="true" style="position: relative;" spellcheck="false">
                        The latest and greatest from TinyMCE
                    </h2> -->
                    <button id="image-upload-btn" href="#" class="btn btn-sm btn-info mb-5">Image <i class="icon-camera ml-1"></i> </button>
                    <div class="mb-3" id="imagePreview"></div>
                    <!-- <input type="hidden" name="{{ form.author.name }}" id="{{ form.author.id_for_label }}"
                        value="{{ user.pk }}"> -->
                    <input value="{{ post.status }}" type="hidden" name="{{ form.status.name }}" id="{{ form.status.id_for_label }}">
                    <input value="{{ post.title }}" type="text" name="{{ form.title.name }}" id="{{ form.title.id_for_label }}"
                        class="form-control title mb-3 dfree-header mce-content-body" contenteditable="true" style="position: relative;" spellcheck="false"
                            placeholder="Story Title" autocomplete="off" required>
                    <textarea name="{{ form.body.name }}" id="{{ form.body.id_for_label }}" 
                        rows="30" autocomplete="off" required>{{ post.body }}</textarea>
                    <div class="d-flex">
                        <!-- <button id="draft-btn" class="btn btn-sm btn-secondary mr-auto mt-3">Save as draft</button> -->
                        <button id="update-btn" class="btn btn-sm btn-primary ml-auto mt-3">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </main>

{% endblock start_container %}
 

{% block end_container %}

    <script type="text/javascript">
        const imageInput = document.querySelector("#image-upload-btn");
        const fileInput = document.querySelector("#{{ form.image.id_for_label | safe }}");
        const imagePreview = document.querySelector("#imagePreview");
        const updateBtn = document.querySelector('#update-btn');

        // imagePreview.style.backgroundImage = `url(${fileInput.value})`;

        imageInput.onclick = () => {
            fileInput.click()
        }
        fileInput.onchange = () => {
            if (fileInput.files && fileInput.files[0]){
                let reader = new FileReader();

                reader.onload = function (e) {
                    imagePreview.style.display = "block";
                    imagePreview.style.backgroundImage = `url('${e.target.result}')`;
                }
                reader.readAsDataURL(fileInput.files[0]);
            }
        }

        updateBtn.onclick = (e) => {
            // document.querySelector('#{{ form.status.id_for_label | safe }}').value = "published";
            document.querySelector('form').submit();
        }
        
    </script>

{% endblock end_container %}

templates/blog/posts/post.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style_link %}
    <link rel="stylesheet" href="{% static 'css/explore.css' %}" />
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
    <style>
        .tag {
            cursor: pointer;
            font-size: 14px;
        }
    </style>
{% endblock %}


{% block start_container %}

    <main>
        <div class="container">
            
            <div class="row mb-5">
              <div class="col-md-8">
                <img class="mb-3" src="{{ post.image.url }}" height="250" />
                <h3 class="pb-4 mb-4 font-italic border-bottom">
                    <i class="icon-tag"></i>
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_by_tag' tag.slug %}" class="tag d-inline-block mb-1 bg-warning bg-secondary rounded-pill p-1 text-decoration-none text-dark">
                            #{{ tag }}
                        </a>
                    {% endfor %}
                </h3>
          
                <div class="blog-post">
                  <h2 class="blog-post-title">{{ post.title }}</h2>
                  <p class="blog-post-meta">{{ post.published_date|date:'F, j Y' }} by <a class="mr-5" href="#">{{ post.author|capfirst }}</a>
                      <span class="ml-5">{{ post.read_duration }} mins </span> <span class="ml-3">{{ post.words_count }} words</span>
                      <span class="ml-5"><i class="icon-clock"></i> {{ post.updated_date }}</span>
                  </p>
                  <hr>
                  <div>
                   {{ post.body | safe }}
                    </div>
                </div>

              </div>
          
              <aside class="col-md-4">
                <div class="p-4 mb-3 bg-light rounded">
                  <h4 class="font-italic">About Author</h4>
                  <p class="mb-0">
                      {% if request.user.profile.about %}
                          {{ request.user.profile.about }}
                      {% else %}
                          No About
                      {% endif %}
                  </p>
                </div>
          
                <div class="p-4">
                  <h4 class="font-italic">Archives</h4>
                  <ol class="list-unstyled mb-0">
                    <li><a href="#">March 2014</a></li>
                    <li><a href="#">February 2014</a></li>
                    <li><a href="#">January 2014</a></li>
                    <li><a href="#">December 2013</a></li>
                    <li><a href="#">November 2013</a></li>
                    <li><a href="#">October 2013</a></li>
                    <li><a href="#">September 2013</a></li>
                    <li><a href="#">August 2013</a></li>
                    <li><a href="#">July 2013</a></li>
                    <li><a href="#">June 2013</a></li>
                    <li><a href="#">May 2013</a></li>
                    <li><a href="#">April 2013</a></li>
                  </ol>
                </div>
          
                <div class="p-4">
                  <h4 class="font-italic">Follow Author</h4>
                  <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                  </ol>
                </div>
              </aside>
          
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <div class="post-content">
                          <div class="post-container">
{#                            <img src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="user" class="profile-photo-md pull-left">#}
                              <span class="icon-user user-icon"></span>
                            <div id="comments" class="post-detail">
                              <div class="user-info">
                                <h5>
                                    <a href="timeline.html" class="profile-link">{{ request.user.first_name }} {{ request.user.last_name }}</a>
                                    <span class="following"><i class="ml-1 icon-user-follow"></i></span>
                                    <span class="float-right">
                                        <a href="#" class="d-inline-block text-decoration-none ml-2"><i class="icon-social-facebook"></i></a>
                                        <a href="#" class="d-inline-block text-decoration-none ml-2"><i class="icon-social-twitter"></i></a>
                                        <a href="#" class="d-inline-block text-decoration-none ml-2"><i class="icon-social-youtube"></i></a>
                                        <a href="#" class="d-inline-block text-decoration-none ml-2"><i class="icon-social-tumblr"></i></a>
                                    </span>
                                </h5>
                                <p class="text-muted">Published an article about 3 days ago </p>
                              </div>
                              <div class="reaction mt-4">
                                <a class="btn text-green"><i class="icon-like"></i> 13</a>
                                <a class="btn text-red"><i class="icon-dislike"></i> 0</a>
                              </div>
                              <div class="line-divider"></div>
                              <div class="post-text">
                                <p>
                                </p>
                              </div>
                              <div class="dropdown-divider"></div>
                                {% for comment in post.comments.all|slice:":2" %}
                              <div class="post-comment bg-light p-3 shadow-sm">
{#                                  <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="" class="profile-photo-sm" />#}
                                  <span style="font-size: x-large" class="icon-user mr-3"></span>
                                  <p><a href="timeline.html" class="profile-link"></a><i class="em em-laughing"></i>
                                      {{ comment.body }}
                                  </p>
                              </div>
                                {% endfor %}
                              <div id="commentInputDiv" class="post-comment">
                                <img src="images/users/user-1.jpg" alt="" class="profile-photo-sm">
                                  <form method="POST" id="comment-form" class="w-100" action="#">
                                      {% csrf_token %}
                                    <input name="{{ form.body.name }}" id="{{ form.body.id_for_label }}" type="text" class="form-control" placeholder="Post a comment">
                                  </form>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr/>
            <div class="container">
                {% if related_post %}
                    <h3>Related Posts</h3>
                {% else %}
                    <h3>No Related Post</h3>
                {% endif %}

                <div style="overflow-x: scroll; -ms-overflow-style: none;" ::-webkit-scrollbar="display: none" class="row">
                    {% for related_post in related_posts %}
                        <div style="height: 150px; overflow-y: hidden;" class="col-md-4 post-container mb-3">
                            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                                <div class="col p-4 pl-2 pt-2 d-flex flex-column position-static">
                                    <strong class="d-inline-block mb-2 text-primary">
                                        {% for tag in related_post.tags.all|slice:":1" %}
                                            #{{ tag }}
                                        {% endfor %}
                                    </strong>
                                    <h6 class="mb-0 font-weight-bold">{{ related_post.title }}</h6>
{#                                    <div style="font-size: small" class="mb-1 text-muted">{{ post.published_date }}</div>#}
                                    <div class="card-text mb-auto">
                                        {{ post.body | truncatechars:70 | safe }}
                                    </div>
                                    <a style="font-size: small" href="{{ related_post.get_absolute_url }}" class="stretched-link">Continue reading</a>
                                </div>
                                <div class="col-md-auto d-none d-lg-block">
                                    <div height="150px" class="post-image" img_src="{{ related_post.image.url }}"></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <hr/>
        </div>
    </main>

{% endblock start_container %}

{% block end_container %}
    <script type="text/javascript" src="{% static 'js/explore.js' %}"></script>
    <script>
        const commentsContainer = document.querySelector("#comments");
        const allComments = document.querySelectorAll(".post-comment");
        const commentInputDiv = document.querySelector("#commentInputDiv");
        const commentForm = document.getElementById("comment-form");
        const commentInput = document.getElementById("{{ form.body.id_for_label }}");

        let test = "something"
        let response = ""

        commentForm.onsubmit = (e) => {
            e.preventDefault();
            const xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    const responseData = this.response;
                    console.log(this.responseText)
                    console.log(this.responseType)
                    console.log(this.response);
                    test = this.response

                    // Comment Div
                    let comment = document.createElement("div")
                    comment.classList.add("post-comment");

                    // User Image
                    let userImage = document.createElement("img")
                    userImage.setAttribute("src", "{{ request.user.profile.pic }}");

                    // Comment Body
                    let commentBody = document.createElement("p")
                    commentBody.innerText += responseData.body;

                    comment.appendChild(userImage);
                    comment.appendChild(commentBody);
                    const pos = allComments.length - 1;
                    commentInputDiv.insertAdjacentElement("beforebegin", comment);

                    {#allComments[allComments.length - 2].insertAdjacentElement()#}
                }
            }
            xhttp.open("POST", "{% url 'blog:add_post_comment' post.slug %}");
            xhttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            xhttp.send(`body=${commentInput.value}`);

            const formData = new FormData()
            formData.append("body", commentInput.value);
            commentInput.value = "";
            {#console.log(typeof(`body=${commentInput.value}`));#}
        }
    </script>
{% endblock end_container %}