authentication/urls.py
from django.urls import path 

from authentication.views import (
    login, logout, signup,
)

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup"),
]

app_name = "authentication"

blog/urls.py
from django.urls import path

from .views.blog import (
    post_list, post_detail, post_add, edit_post, my_stories,
    post_by_tag, delete_post,
    add_post_comment,
)

from .views import errors


app_name = 'blog'

urlpatterns = [
    path('all/', post_list, name="post_list"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', post_detail, name="post_detail"),
    path('post/new/', post_add, name="post_add"),
    path('post/<slug:slug>/edit/', edit_post, name="post_edit"),
    path('post/delete/<int:year>/<int:month>/<int:day>/<slug:slug>/', delete_post, name="post_delete"),
    path('post/my_stories/', my_stories, name="my_stories"),
    path('all/tags/<slug:slug>/', post_by_tag, name="post_by_tag"),
    path('post/<slug:slug>/comment/add/', add_post_comment, name="add_post_comment"),
]

#  Error views
handler404 = errors.handler404

kaliblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blog.views.blog import index


urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('posts/', include('blog.urls', namespace='blog')),
    path('authentication/', include('authentication.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blog.views import index


urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('posts/', include('blog.urls', namespace='blog')),
    path('authentication/', include('authentication.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'simple-line-icons.min.css' %}">
    {% block custom_style_link %}{% endblock %}
    <!-- <link rel="stylesheet" href="{% static 'css/custom_style.css' %}"> -->
    <title>Blog for everyone</title>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
</head>
<body class="{% block body_class %}{% endblock body_class %}">
    {% block header %}
    <header>
        {% block carousel %} {% endblock %}
        <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top shadow">
            <div class="container-fluid">
                <a href="{% url 'home' %}" class="navbar-brand font-weight-bold text-dark text-decoration-underline">KaliBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavigation" aria-label="Main Page Navigation" aria-controls="mainNavigation" aria-expanded="false">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="mainNavigation">
                    <ul class="navbar-nav ml-5 mr-auto mb-2 mb-md-0">
                        <li class="nav-item {{ home_active }}"><a href="/" class="nav-link">Home <i class="icon-home"></i> </a></li>
                        <li class="nav-item {{ explore_active }}"><a href="{% url 'blog:post_list' %}" class="nav-link">Explore <i class="icon-notebook"></i> </a></li>
                        <li class="nav-item {{ subscribe_active }}">
                            <div class="dropdown">
                                <a id="subscribe-btn" data-toggle="dropdown" aria-expanded="false" role="button" href="#" class="nav-link">Subscribe <i class="icon-feed"></i> </a>
                                <div class="dropdown-menu bg-info">
                                    <form method="POST" action="#" style="min-width: 26rem" class="px-4 py-3 row g-3">
                                        <div class="col-auto">
                                            <input type="email" class="form-control" placeholder="Enter your email...">
                                        </div>
                                      <div class="col-auto">
                                        <button type="submit" class="btn btn btn-primary">Subscribe!</button>
                                      </div>
                                  </form>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item {{ about_us_active }}"><a href="#" class="nav-link">About Us</a></li>
                    </ul>
                    <div class="d-flex mr-5">
                        {% if not user.is_authenticated %}
                            <a href="{% url 'authentication:login' %}" class="btn btn-sm btn-primary">Login <i class="ml-1 icon-key"></i> </a>
                        {% else %}
                            <div class="dropdown mr-5">
                                <a style="text-decoration: none" href="#" class="dropdown-toggle text-dark" id="userAuthDropdown" data-toggle="dropdown" aria-expanded="false">
                                    <i class="icon-user"></i>
{#                                    {{ user.first_name|capfirst }}#}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="userAuthDropdown">
                                    <li><a class="dropdown-item" href="{% url 'blog:my_stories' %}">My Stories</a></li>
                                    <li><a class="dropdown-item" href="{% url 'blog:post_add' %}">New Story <i class="icon-pencil ml-1"></i> </a></li>
                                    <div class="dropdown-divider"></div>
                                    <li><a class="dropdown-item" href="{% url 'authentication:logout' %}">Logout <i class="ml-1 icon-power"></i> </a></li>
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    {% endblock header %}
    {% block start_container %}{% endblock start_container%}
    {% block end_container %}{% endblock end_container %}
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html> 

templates/footer.html
 <!-- Footer -->
  <footer class="footer bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item">
              <a href="#">About</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Contact</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Terms of Use</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Privacy Policy</a>
            </li>
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">&copy; KaliBlog 2020. All Rights Reserved.</p>
        </div>
        <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
          <ul class="list-inline mb-0">
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-facebook fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-twitter-square fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-instagram fa-2x fa-fw"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style_link %} 
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}" /> 
{% endblock %}

{% block carousel %}

<div class="carousel slide" id="homepageCarousel" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#homepageCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#homepageCarousel" data-slide-to="1"></li>
        <li data-target="#homepageCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="carousel-bg-image" img_src="{% static 'images/write4.jpg' %}"></div>
            <div class="container">
                <div class="carousel-caption text-left">
                    <h1>What's on your mind</h1>
                    <p>
                        Express your thoughts through writing of stories. Share your experience, knowledge and awesome ideas
                        to people out there. Remember, you learn more by sharing and teaching more.
                    </p>
                    <p><a href="{% url 'blog:post_add' %}" role="button" class="btn btn-lg btn-primary">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="carousel-bg-image" img_src="{% static 'images/read.jpg' %}"></div>
            <div class="container">
                <div class="carousel-caption">
                    <h1>Know More</h1>
                    <p>
                        Read ideas and knowledge from world class great authors. "You are only limited
                        by the thoughts, and your thoughts are affected by things your read", A Physichologist
                        said.
                    </p>
                    <p><a href="{% url 'blog:post_list' %}" class="btn btn-lg btn-primary">Explore Articles</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="carousel-bg-image" img_src="{% static 'images/join2.jpg' %}"></div>
            <div class="container">
                <div class="carousel-caption text-right">
                    <h1>Meet People</h1>
                    <p>
                        Join our community which consist of diverse group of individuals with a wide variety
                        of field of speciality from all over the world.
                    </p>
                    <p><a href="#" class="btn btn-lg btn-primary">Forum</a></p>
                </div>
            </div>
        
        </div>
    <a class="carousel-control-prev" href="#homepageCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#homepageCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
</div>
{% endblock %}

{% block start_container %}
    <main style="margin-top: 0;">
        <div class="features-icons bg-light text-center">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-4">
                      <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                        <div class="features-icons-icon d-flex">
                          <i class="icon-screen-desktop m-auto text-primary"></i>
                        </div>
                        <h3>Fully Responsive</h3>
                        <p class="lead mb-0">This UI looks great on any device, no matter the size!</p>
                      </div>
                    </div>

                    <div class="col-lg-4">
                      <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                        <div class="features-icons-icon d-flex">
                          <i class="icon-layers m-auto text-primary"></i>
                        </div>
                        <h3>Bootstrap 5 Styled</h3>
                        <p class="lead mb-0">Featuring the latest build of the new Bootstrap 4 framework!</p>
                      </div>
                    </div>

                    <div class="col-lg-4">
                      <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                        <div class="features-icons-icon d-flex">
                          <i class="icon-check m-auto text-primary"></i>
                        </div>
                        <h3>Easy to Use</h3>
                        <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
                      </div>
                    </div>

                </div>
            </div>
        </div>
        <section class="showcase">
            <div class="container-fluid p-0">
              <div class="row no-gutters">

                <div class="col-lg-6 order-lg-2 text-white showcase-img" img_src="{% static 'images/responsive-bg.jpg' %}"></div>
                <div class="col-lg-6 order-lg-1 my-auto showcase-text p-5">
                  <h2>Fully Responsive Design</h2>
                  <p class="lead mb-0">
                      Greatly improved user interface and responsive using bootstrap. No matter the screensize, it looks real great and feels warm to use.
                  </p>
                </div>
              </div>
              <div class="row no-gutters">
                <div class="col-lg-6 text-white showcase-img" img_src="{% static 'images/code-integration-bg.jpg' %}"></div>
                <div class="col-lg-6 my-auto showcase-text p-5">
                  <h2>Easy Code Integration</h2>
                  <p class="lead mb-0">
                      Easy code integration when writing an article or a story that require that you use a code snippet. There is an inbuilt support with tinymce
                      that helps creating of articles easier with an WYSIWYG editor that is easy to use and user friendly.
                  </p>
                </div>
              </div>
              <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" img_src="{% static 'images/easy-customization-bg.jpg' %}"></div>
                <div class="col-lg-6 order-lg-1 my-auto showcase-text p-5">
                  <h2>Easy to Use</h2>
                  <p class="lead mb-0">
                      When it comes to User Interface and Experience, KaliBlog nailed it there. Operations and command buttons or menus are easy to locate
                      and are self explanatory. You'll find working with KaliBlog community a great deal.
                  </p>
                </div>
              </div>
            </div>
          </section>
        <section class="team-container text-center bg-light">
            <div class="container">
              <h2 class="mb-5">Our Professional Team Members</h2>
              <div class="row">
                <div class="col-lg-4">
                  <div class="team-item mx-auto mb-5 mb-lg-0">
                    <img class="img-fluid rounded-circle mb-3" src="{% static 'images/profile.png' %}" alt="">
                    <h5>Dr. Desmond Brown.</h5>
                    <p class="font-weight-light mb-0">Doctrate Degree in Biomedical Engineering</p>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="team-item mx-auto mb-5 mb-lg-0">
                    <img class="img-fluid rounded-circle mb-3" src="{% static 'images/profile.png' %}" alt="">
                    <h5>Dr. Kali Junior Brown.</h5>
                    <p class="font-weight-light mb-0">Masters Degree in Artificial Intelligence</p>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="team-item mx-auto mb-5 mb-lg-0">
                    <img class="img-fluid rounded-circle mb-3" src="{% static 'images/profile.png' %}" alt="">
                    <h5>Dr. Kali Brown.</h5>
                    <p class="font-weight-light mb-0">Bachelor of Science in Computer Science</p>
                  </div>
                </div>
              </div>
            </div>
          </section>

        <section class="call-to-action text-white text-center">
{#            <div class="overlay"></div>#}
            <div class="container">
              <div class="row">
                <div class="col-xl-9 mx-auto">
                  <h2 class="mb-4">Ready to get started? Sign up now!</h2>
                </div>
                <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                  <form>
                    <div class="form-row">
                      <div class="col-12 col-md-9 mb-2 mb-md-0">
                        <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
                      </div>
                      <div class="col-12 col-md-3">
                        <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
        </section>
    </main>

    {% include 'footer.html' %}
{% endblock start_container %}

{% block end_container %}
    <script type="text/javascript" src="{% static 'js/carousel.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/explore.js' %}"></script>
    <script>
        const imageDivs = document.querySelectorAll(".showcase-img")
        Array.from(imageDivs).map(image=> {
            image.style.backgroundImage = `url(${image.getAttribute("img_src")})`
        })
    </script>
{% endblock end_container %}